apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack

resources:
- ../../base/

# Ensure no glance pods are running yet
# Disable eight services unnecessary for Glance
patches:
  - patch: |-
      - op: replace
        path: /spec/glance/template/glanceAPIs/default/replicas
        value: 0
      - op: replace
        path: /spec/glance/template/storageClass
        value: "local-storage"
      - op: add
        path: /spec/cinder/enabled
        value: false
      - op: add
        path: /spec/neutron/enabled
        value: false
      - op: add
        path: /spec/nova/enabled
        value: false
      - op: add
        path: /spec/rabbitmq/enabled
        value: false
      - op: add
        path: /spec/placement/enabled
        value: false
      - op: add
        path: /spec/ovn/enabled
        value: false
      - op: add
        path: /spec/swift/enabled
        value: false
      - op: add
        path: /spec/heat/enabled
        value: false
      - op: add
        path: /spec/horizon/enabled
        value: false
    target:
      kind: OpenStackControlPlane
