apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: nova-custom-ceph
spec:
  label: dataplane-deployment-nova-custom-ceph
  configMaps:
    - libvirt-qemu-nova
    - ceph-nova
  secrets:
    - nova-cell1-compute-config
  playbook: osp.edpm.nova
