apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: firewall
spec:
  label: dataplane-deployment-firewall
  role:
    name: ""
    hosts: "all"
    strategy: "linear"
    tasks:
    - name: Configure firewall
      import_role:
          name: osp.edpm.edpm_nftables
          tasks_from: "configure.yml"
    - name: Reload firewall
      import_role:
          name: osp.edpm.edpm_nftables
          tasks_from: "run.yml"
