apiVersion: test.openstack.org/v1beta1
kind: Tempest
metadata:
  name: tempest-tests
  namespace: openstack
spec:
  SELinuxLevel: s0:c478,c978
  SSHKeySecretName: test-operator-controller-priv-key
  backoffLimit: 0
  containerImage: quay.io/podified-antelope-centos9/openstack-tempest-all:current-podified
  networkAttachments:
  - ctlplane
  openStackConfigMap: openstack-config
  openStackConfigSecret: openstack-config-secret
  parallel: false
  storageClass: lvms-local-storage
  tempestRun:
    concurrency: 8
    includeList: |
      ^tempest.api.object_storage.*
      ^tempest.scenario.test_object_storage_basic_ops.*
    excludeList: |
      # https://bugzilla.redhat.com/2102593
      ^tempest.api.object_storage.test_container_quotas.ContainerQuotasTest.test_upload_too_many_objects
      # https://bugzilla.redhat.com/2284163
      ^tempest.api.object_storage.test_container_services.ContainerTest.test_update_container_metadata_with_delete_metadata
      ^tempest.api.object_storage.test_container_services.ContainerTest.test_update_container_metadata_with_delete_metadata_key
      # https://bugzilla.redhat.com/2209078
      ^tempest.api.object_storage.test_container_services.ContainerTest.test_create_container_with_remove_metadata_key
      ^tempest.api.object_storage.test_container_services.ContainerTest.test_create_container_with_remove_metadata_value
      # https://bugzilla.redhat.com/2284026
      ^tempest.api.object_storage.test_container_services.ContainerTest.test_update_container_metadata_with_create_and_delete_metadata
      # other excludes
      ^tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate
      ^tempest.api.compute.admin.test_live_migration.LiveMigrationTest.test_live_block_migration_paused
      ^tempest.api.compute.admin.test_live_migration.LiveAutoBlockMigrationV225Test.test_live_block_migration_paused
      ^tempest.api.compute.admin.test_live_migration.LiveMigrationRemoteConsolesV26Test.test_live_block_migration_paused
      ^neutron_plugin.tests.scenario.test_sriov.*
      ^neutron_plugin.tests.scenario.test_l3ha_ovn.*
      ^neutron_plugin.tests.scenario.test_provider_network.*
      ^neutron_plugin.tests.scenario.test_multicast.MulticastTestIPv4Sriov.*
      ^neutron_plugin.tests.scenario.test_qos.QosTestSriov.*
      test_multicast.*restart
      ^neutron_plugin.*test_qos_user_policies
      ^neutron_plugin.tests.scenario.test_qos.QosTestExternalNetwork.*
      ^neutron_plugin.*many_vms
      ^neutron_plugin.*test_previously_used_ip
      ^neutron_plugin.tests.scenario.test_ovn_dbs.OvnDbsMonitoringTest.*
      ^neutron_tempest_plugin.*test_port_forwarding_to_2_fixed_ips
      ^neutron_plugin.tests.scenario.test_internal_dns.InternalDNSInterruptions.*
      ^neutron_plugin.*reboot_node
      ^neutron_plugin.*networker_reboot
      ^neutron_plugin.*ovn_controller_restart
      test_encrypted_cinder_volumes_cryptsetup
    externalPlugin: []
    extraImages: []
    neutronExtraImage: ""
    parallel: true
    serial: false
    smoke: false
    workerFile: ""
  tempestconfRun:
    append: ""
    collectTiming: false
    convertToRaw: false
    create: true
    createAccountsFile: ""
    debug: false
    deployerInput: |
      [object-storage]
      operator_role = swiftoperator
      reseller_admin_role = ResellerAdmin
    flavorMinDisk: 0
    flavorMinMem: 0
    generateProfile: ""
    image: ""
    imageDiskFormat: ""
    insecure: false
    networkID: ""
    noDefaultDeployer: false
    nonAdmin: false
    out: ""
    overrides: |
       auth.tempest_roles member,swiftoperator
       auth.admin_username admin
       auth.admin_project_name admin
       auth.admin_domain_name Default      
       object-storage-feature-enabled.discoverability false
       compute-feature-enabled.attach_encrypted_volume true
       compute-feature-enabled.live_migration true
       compute-feature-enabled.volume_multiattach true
       volume-feature-enabled.extend_attached_volume true
       volume-feature-enabled.volume_revert true
       volume.volume_type_multiattach multiattach
       share.capability_storage_protocol CEPHFS
       share.run_share_group_tests False
       share.suppress_errors_in_cleanup True
       share.enable_cephx_rules_for_protocols cephfs
       share.storage_protocol CEPHFS
       share.enable_cert_rules_for_protocols ""
       share.enable_ip_rules_for_protocols ""
       share.storage_network storage
       ds_neutron_plugin_options.mechanism_driver ovn
       neutron_plugin_options.available_type_drivers geneve
    profile: ""
    remove: |
      network-feature-enabled.api_extensions dhcp_agent_scheduler,qos,trunk
    retryImage: false
    testAccounts: ""
    timeout: 0
    verbose: false
  workflow: []
