apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack

resources:
- ../../base/
 
patches:
  - patch: |-
      - op: add
        path: /spec/nodeTemplate/extraMounts
        value:
          - extraVolType: edpm-ansible
            mounts:
            - mountPath: /usr/share/ansible/collections/ansible_collections/osp/edpm
              name: edpm-ansible
            volumes:
            - name: edpm-ansible
              persistentVolumeClaim:
                claimName: edpm-ansible
                readOnly: true
          - extraVolType: Logs
            mounts:
            - mountPath: /runner/artifacts
              name: ansible-logs
            volumes:
            - name: ansible-logs
              persistentVolumeClaim:
                claimName: ansible-ee-logs
    target:
      kind: OpenStackDataPlaneNodeSet
