apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: deployment-pre-ceph
  namespace: openstack
spec:
  nodeSets:
    - openstack-edpm
  servicesOverride:
    - repo-setup
    - configure-network
    - validate-network
    - install-os
    - ceph-hci-pre
    - configure-os
    - run-os
