apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlane
metadata:
  name: openstack-edpm
  namespace: openstack
spec:
  roles:
    edpm-compute:
      nodeTemplate:
        nova:
          customServiceConfig: |
            [libvirt]
            virt_type = qemu
      # remove repo-setup from services list
      services:
        - configure-network
        - validate-network
        - install-os
        - configure-os
        - run-os
      # deploy all nodes (role level)
      deployStrategy:
        deploy: false
  # deploy all nodes (node level)
  nodes:
    edpm-compute-0:
      deployStrategy:
        deploy: false
    edpm-compute-1:
      deployStrategy:
        deploy: false
    edpm-compute-2:
      deployStrategy:
        deploy: false
  # deploy all nodes (spec level)
  deployStrategy:
    deploy: true
