apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlane
metadata:
  name: openstack-edpm
  namespace: openstack
spec:
  roles:
    edpm-compute:
      # remove repo-setup from services list
      services:
        - configure-network
        - validate-network
        - install-os
        - configure-os
        - run-os
        - ovn
        - libvirt
        - nova
