apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlane
metadata:
  name: openstack-edpm
  namespace: openstack
spec:
  roles:
    edpm-compute:
      nodeTemplate:
        extraMounts:
        - extraVolType: edpm-ansible
          mounts:
          - mountPath: /usr/share/ansible/collections/ansible_collections/osp/edpm
            name: edpm-ansible
          volumes:
          - name: edpm-ansible
            persistentVolumeClaim:
              claimName: edpm-ansible
              readOnly: true
        nova:
          customServiceConfig: |
            [libvirt]
            virt_type = qemu
      # remove repo-setup from services list
      services:
        - configure-network
        - validate-network
        - install-os
        - configure-os
        - run-os
