---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-ceph
data:
  03-nova-ceph: |
    [libvirt]
    virt_type = qemu
    images_type=rbd
    images_rbd_pool=vms
    images_rbd_ceph_conf=/etc/ceph/ceph.conf
    images_rbd_glance_store_name=default_backend
    images_rbd_glance_copy_poll_interval=15
    images_rbd_glance_copy_timeout=600
    rbd_user=openstack
    rbd_secret_uuid=_FSID_
