apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlane
metadata:
  name: openstack-edpm
  namespace: openstack
spec:
  # deploy all nodes (role level)
  roles:
    edpm-compute:
      deployStrategy:
        deploy: true
  # deploy all nodes (node level)
  nodes:
    edpm-compute-0:
      deployStrategy:
        deploy: true
    edpm-compute-1:
      deployStrategy:
        deploy: true
    edpm-compute-2:
      deployStrategy:
        deploy: true
  # deploy all nodes (spec level)
  deployStrategy:
    deploy: true
