apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack

resources:
- ../../base/
 
# Do not deploy nova yet, but configure network, ntp and ceph firewall ports
patches:
  - patch: |-
      - op: replace
        path: /spec/roles/edpm-compute/services
        value:
          - configure-network
          - validate-network
          - install-os
          - configure-os
          - ceph-hci-pre
          - run-os
      - op: add
        path: /spec/roles/edpm-compute/nodeTemplate/extraMounts
        value:
          - extraVolType: edpm-ansible
            mounts:
            - mountPath: /usr/share/ansible/collections/ansible_collections/osp/edpm
              name: edpm-ansible
            volumes:
            - name: edpm-ansible
              persistentVolumeClaim:
                claimName: edpm-ansible
                readOnly: true
          - extraVolType: Logs
            mounts:
            - mountPath: /runner/artifacts
              name: ansible-logs
            volumes:
            - name: ansible-logs
              persistentVolumeClaim:
                claimName: ansible-ee-logs
    target:
      kind: OpenStackDataPlane
