apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlane
metadata:
  name: openstack-edpm
  namespace: openstack
spec:
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
          - CinderVolume
          - GlanceAPI
          extraVolType: Ceph
          volumes:
          - name: ceph
            projected:
              sources:
              - secret:
                  name: ceph-conf-files
          mounts:
          - name: ceph
            mountPath: "/etc/ceph"
            readOnly: true
  roles:
    edpm-compute:
      nodeTemplate:
        nova:
          customServiceConfig: |
            [libvirt]
            virt_type = qemu
            images_type=rbd
            images_rbd_pool=vms
            images_rbd_ceph_conf=/etc/ceph/ceph.conf
            images_rbd_glance_store_name=default_backend
            images_rbd_glance_copy_poll_interval=15
            images_rbd_glance_copy_timeout=600
            rbd_user=openstack
            rbd_secret_uuid=_FSID_
      # remove repo-setup from services list
      services:
        - configure-network
        - validate-network
        - install-os
        - configure-os
        - run-os

  # because edpm-compute-0 is just an external ceph VM
  nodes:
    edpm-compute-0:
      deployStrategy:
        deploy: false
    edpm-compute-1:
      deployStrategy:
        deploy: true
            
