apiVersion: topology.openstack.org/v1beta1
kind: Topology
metadata:
  name: storage-topology
  namespace: openstack
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - zoneA
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: service
              operator: In
              values:
              - glance
          topologyKey: kubernetes.io/hostname
        weight: 80
  topologySpreadConstraint:
  - labelSelector:
      matchLabels:
        service: glance
    maxSkew: 3
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
