apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlane
metadata:
  name: openstack-edpm
  namespace: openstack
spec:
  extraMounts:
    - extraVol:
        - extraVolType: Ceph
          volumes:
          - name: ceph
            projected:
              sources:
              - secret:
                  name: ceph-conf-files
          mounts:
          - name: ceph
            mountPath: "/etc/ceph"
            readOnly: true
  roles:
    edpm-compute:
      # restore rest of the services list
      services:
        - ceph-client
        - ovn
        - libvirt
        - nova-custom-ceph
